/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javafx.scene.paint.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author PHUC
 */
public class DashBoard extends javax.swing.JFrame {

    private List<JButton> listButton = new ArrayList<>();
    private static final int DASHBOARD = 0;
    private static final int REPOSITORY = 1;
    private static final int STATISTIC = 2;
    private static final int REPORT = 3;
    private static final int IMPORT = 4;
    private static final int LOGOUT = 5;
    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        init();
        SwingUtilities.updateComponentTreeUI(this);
    }
    
    private void  init(){
        this.workPlace.setBounds(this.getBounds());
        this.listButton.add(this.btnDashboard);
        this.listButton.add(this.btnRepository);
        this.listButton.add(this.btnStatistic);
        this.listButton.add(this.btnReport);
        this.listButton.add(this.btnImport);
        this.listButton.add(this.btnLogout);
//        this.jToolBar1.setBackground(Color.white);
//        this.btnDashboard.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workPlace = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnDashboard = new javax.swing.JButton();
        btnRepository = new javax.swing.JButton();
        btnStatistic = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        workPlace.setBackground(new java.awt.Color(255, 255, 255));
        workPlace.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setFocusable(false);
        btnDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboard.setMaximumSize(new java.awt.Dimension(97, 67));
        btnDashboard.setMinimumSize(new java.awt.Dimension(97, 67));
        btnDashboard.setPreferredSize(new java.awt.Dimension(97, 67));
        btnDashboard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDashboard);

        btnRepository.setBackground(new java.awt.Color(255, 255, 255));
        btnRepository.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRepository.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repository.png"))); // NOI18N
        btnRepository.setText("Quản lí kho");
        btnRepository.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepository.setFocusable(false);
        btnRepository.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRepository.setMaximumSize(new java.awt.Dimension(97, 67));
        btnRepository.setMinimumSize(new java.awt.Dimension(97, 67));
        btnRepository.setPreferredSize(new java.awt.Dimension(97, 67));
        btnRepository.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRepository.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepositoryActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRepository);

        btnStatistic.setBackground(new java.awt.Color(255, 255, 255));
        btnStatistic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnStatistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/statistic.png"))); // NOI18N
        btnStatistic.setText("Thống kê");
        btnStatistic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStatistic.setFocusable(false);
        btnStatistic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStatistic.setMaximumSize(new java.awt.Dimension(97, 67));
        btnStatistic.setMinimumSize(new java.awt.Dimension(97, 67));
        btnStatistic.setPreferredSize(new java.awt.Dimension(97, 67));
        btnStatistic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStatistic);

        btnReport.setBackground(new java.awt.Color(255, 255, 255));
        btnReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btnReport.setText("Báo cáo");
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.setFocusable(false);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setMaximumSize(new java.awt.Dimension(97, 67));
        btnReport.setMinimumSize(new java.awt.Dimension(97, 67));
        btnReport.setPreferredSize(new java.awt.Dimension(97, 67));
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReport);

        btnImport.setBackground(new java.awt.Color(255, 255, 255));
        btnImport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/import.png"))); // NOI18N
        btnImport.setText("Import");
        btnImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImport.setFocusable(false);
        btnImport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImport.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnImport.setMaximumSize(new java.awt.Dimension(97, 67));
        btnImport.setMinimumSize(new java.awt.Dimension(97, 67));
        btnImport.setPreferredSize(new java.awt.Dimension(97, 67));
        btnImport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImport);

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(97, 67));
        btnLogout.setMinimumSize(new java.awt.Dimension(97, 67));
        btnLogout.setPreferredSize(new java.awt.Dimension(97, 67));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setMaximumSize(new java.awt.Dimension(97, 67));
        btnThoat.setMinimumSize(new java.awt.Dimension(97, 67));
        btnThoat.setPreferredSize(new java.awt.Dimension(97, 67));
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThoat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workPlace)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        changeFrame(DASHBOARD);
        IDashBoard frame = new IDashBoard();

        this.workPlace.removeAll();
        this.workPlace.add(frame);
        frame.setPreferredSize(this.workPlace.getPreferredSize());

        //frame.setUndecorated(true);
        frame.setVisible(true);
        frame.setResizable(false);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnRepositoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepositoryActionPerformed
        // TODO add your handling code here:
        changeFrame(REPOSITORY);
        IRepository frame = new IRepository();
        this.workPlace.removeAll();
        this.workPlace.add(frame);
        frame.setPreferredSize(this.workPlace.getPreferredSize());

        //frame.setUndecorated(true);
        frame.setVisible(true);
        frame.setResizable(false);
    }//GEN-LAST:event_btnRepositoryActionPerformed

    private void btnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticActionPerformed
        // TODO add your handling code here:
        changeFrame(STATISTIC);
    }//GEN-LAST:event_btnStatisticActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        changeFrame(REPORT);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        DImport dImport = new DImport(this, true);
        dImport.setResizable(false);
        dImport.setLocationRelativeTo(btnImport);
        dImport.setVisible(true);
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
       changeFrame(LOGOUT);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnThoatActionPerformed

    private void changeFrame(int index){
        this.listButton.get(index).setEnabled(false);
        for(int i=0;i<listButton.size();i++){
            if(i != index){
                listButton.get(i).setEnabled(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnRepository;
    private javax.swing.JButton btnStatistic;
    private javax.swing.JButton btnThoat;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane workPlace;
    // End of variables declaration//GEN-END:variables
}
