/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DatabaseAPI;
import datamodel.DataComboBoxStringModel;
import entities.Bill;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jboss.jdeparser.JOp;

/**
 *
 * @author PHUC
 */
public class DChangeStatus extends javax.swing.JDialog {
    private IStatistic iStatistic;
    private int page;
    private Bill bill;
    private List<String> listStatus;
    private DataComboBoxStringModel model;
    /**
     * Creates new form DChangeStatus
     */
    public DChangeStatus(java.awt.Frame parent, boolean modal, IStatistic iStatistic, Bill bill, int page) {
        super(parent, modal);
        this.iStatistic = iStatistic;
        this.page = page;
        this.bill = bill;
        initComponents();
        init();
    }

    private void init(){
        listStatus = new ArrayList<>();
        listStatus.add("ĐÃ THANH TOÁN");
        listStatus.add("CHƯA THANH TOÁN");
        this.model = new DataComboBoxStringModel(listStatus);
        this.cbbStatus.setModel(model);
        this.cbbStatus.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbStatus = new javax.swing.JComboBox<>();
        btnChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnChange.setText("Đổi");
        btnChange.setContentAreaFilled(false);
        btnChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChange)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        String status = this.cbbStatus.getSelectedItem().toString();
        bill.setStatus(status);
        boolean ok = DatabaseAPI.updateBill(bill);
        if(ok){
            this.setVisible(false);
            JOptionPane.showMessageDialog(iStatistic, "Đổi trạng thái thành công!", "Information", JOptionPane.INFORMATION_MESSAGE);
            this.iStatistic.loadData(page);
        }else{
            JOptionPane.showMessageDialog(iStatistic, "Đổi trạng thái thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JComboBox<String> cbbStatus;
    // End of variables declaration//GEN-END:variables
}
