/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import charts.ChartBestSell;
import charts.ChartRevenue;
import common.CommonFunction;
import datamodel.DataComboBoxStringModel;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileSystemView;
import pdf.PDFPrint;
import report.ReportForm;

/**
 *
 * @author PHUC
 */
public class DChooseOptionReport extends javax.swing.JDialog {

    private int optionChart;
    private int optionDate;
    private List<String> choices;
    private DataComboBoxStringModel model;
    /**
     * Creates new form DChooseOption
     */
    public DChooseOptionReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public void setOption(int option){
        this.optionChart = option;
    }
    
    private void init(){
        choices = new ArrayList<String>();
        choices.add("Tạo báo cáo theo ngày");
        choices.add("Tạo báo cáo theo tháng");
        choices.add("Tạo báo cáo theo năm");
        choices.add("Tạo báo cáo từ ngày đến ngày");
        this.model = new DataComboBoxStringModel(choices);
        this.cbbOption.setModel(model);
        this.pnlFromTo.setVisible(false);
        this.pnlDate.setVisible(false);
        SpinnerModel model1 = new SpinnerNumberModel(1, 1, 31, 1);
        SpinnerModel model12 = new SpinnerNumberModel(1, 1, 31, 1);
        SpinnerModel model2 = new SpinnerNumberModel(1, 1, 12, 1);
        SpinnerModel model22 = new SpinnerNumberModel(1, 1, 12, 1);
        SpinnerModel model3 = new SpinnerNumberModel(2019, 1970, 2050, 1);
        SpinnerModel model32 = new SpinnerNumberModel(2019, 1970, 2050, 1);
        this.txtDate.setModel(model1);
        this.txtDate1.setModel(model12);
        this.txtDate2.setModel(model1);
        this.txtMonth.setModel(model22);
        this.txtMonth1.setModel(model2);
        this.txtMonth2.setModel(model22);
        this.txtYear.setModel(model3);
        this.txtYear1.setModel(model32);
        this.txtYear2.setModel(model3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbOption = new javax.swing.JComboBox<>();
        btnChoice = new javax.swing.JButton();
        pnlFromTo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtMonth = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtYear = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtDate1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtMonth1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        txtYear1 = new javax.swing.JSpinner();
        pnlDate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtDate2 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        txtMonth2 = new javax.swing.JSpinner();
        txtYear2 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbbOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbOptionItemStateChanged(evt);
            }
        });

        btnChoice.setText("Chọn");
        btnChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiceActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ");

        jLabel2.setText("Đến");

        jLabel5.setText("Ngày");

        jLabel6.setText("Tháng");

        jLabel7.setText("Năm");

        jLabel8.setText("Ngày");

        txtDate1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtDate1StateChanged(evt);
            }
        });

        jLabel9.setText("Tháng");

        jLabel10.setText("Năm");

        javax.swing.GroupLayout pnlFromToLayout = new javax.swing.GroupLayout(pnlFromTo);
        pnlFromTo.setLayout(pnlFromToLayout);
        pnlFromToLayout.setHorizontalGroup(
            pnlFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFromToLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFromToLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYear))
                    .addGroup(pnlFromToLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYear1)))
                .addContainerGap())
        );
        pnlFromToLayout.setVerticalGroup(
            pnlFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFromToLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Ngày");

        jLabel12.setText("Tháng");

        jLabel13.setText("Năm");

        javax.swing.GroupLayout pnlDateLayout = new javax.swing.GroupLayout(pnlDate);
        pnlDate.setLayout(pnlDateLayout);
        pnlDateLayout.setHorizontalGroup(
            pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDateLayout.setVerticalGroup(
            pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFromTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cbbOption, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnChoice)
                .addGap(0, 10, Short.MAX_VALUE))
            .addComponent(pnlDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbbOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFromTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbOptionItemStateChanged
        // TODO add your handling code here:
        int index = this.cbbOption.getSelectedIndex();
        this.optionDate = index;
        if(index == 3){
            
            this.pnlFromTo.setVisible(true);
            this.pnlDate.setVisible(false);
            this.pack();
        }else{
            this.pnlFromTo.setVisible(false);
            if(index <= 2 && index > 0){
                this.txtMonth2.setEnabled(false);
                this.txtDate2.setEnabled(false);
            }
            if(index == 1)
                this.txtMonth2.setEnabled(true);
            if(index == 0){
                this.txtMonth2.setEnabled(true);
                this.txtDate2.setEnabled(true);
            }
            this.pnlDate.setVisible(true);
            this.pack();
        }
    }//GEN-LAST:event_cbbOptionItemStateChanged

    private void btnChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiceActionPerformed
        // TODO add your handling code here:
        List<Date> list = new ArrayList<Date>();
        int index = this.cbbOption.getSelectedIndex();
        String dateBeginS, dateEndS, dateS;
        Date dateBegin, dateEnd, date;
        if(index == 3){
            dateBeginS = this.txtDate.getValue().toString() + "-" + this.txtMonth.getValue().toString() + "-" + this.txtYear.getValue().toString();
            dateEndS = this.txtDate1.getValue().toString() + "-" + this.txtMonth1.getValue().toString() + "-" + this.txtYear1.getValue().toString();
            if(dateBeginS.equals("") || dateEndS.equals("")){
                JOptionPane.showMessageDialog(this, "Điền đầy đủ thông tin!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            dateBegin = CommonFunction.parseDate(dateBeginS, "dd-MM-yyyy");
            dateEnd = CommonFunction.parseDate(dateEndS, "dd-MM-yyyy");
            if(dateBegin == null || dateEnd == null){
                JOptionPane.showMessageDialog(this, "Kiểm tra định dạng ngày nhập!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            list.add(dateBegin);
            list.add(dateEnd);
        }else{
            dateS = this.txtDate2.getValue().toString() + "-" + this.txtMonth2.getValue().toString() + "-" + this.txtYear2.getValue().toString();
            if(dateS.equals("")){
                JOptionPane.showMessageDialog(this, "Điền đầy đủ thông tin!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            date = CommonFunction.parseDate(dateS, "dd-MM-yyyy");
            if(date == null){
                JOptionPane.showMessageDialog(this, "Kiểm tra định dạng ngày nhập!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            list.add(date);
        }
        ReportForm form = new ReportForm(list, optionDate);
        JPanel contentReport = form.getContentPanel();
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = fileChooser.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                PDFPrint.generatePDF(contentReport, selectedFile, "REPORT_" + CommonFunction.currentTimeDateFormat());
                JOptionPane.showMessageDialog(this, "Tạo báo cáo thành công!", "Information", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Mở file thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
        }
        //form.setLocationRelativeTo(this);
        //form.setVisible(true);
    }//GEN-LAST:event_btnChoiceActionPerformed

    private void txtDate1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtDate1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoice;
    private javax.swing.JComboBox<String> cbbOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlDate;
    private javax.swing.JPanel pnlFromTo;
    private javax.swing.JSpinner txtDate;
    private javax.swing.JSpinner txtDate1;
    private javax.swing.JSpinner txtDate2;
    private javax.swing.JSpinner txtMonth;
    private javax.swing.JSpinner txtMonth1;
    private javax.swing.JSpinner txtMonth2;
    private javax.swing.JSpinner txtYear;
    private javax.swing.JSpinner txtYear1;
    private javax.swing.JSpinner txtYear2;
    // End of variables declaration//GEN-END:variables
}
