/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DatabaseAPI;
import datamodel.DataModelRepository;
import entities.Inventory;
import java.util.ArrayList;
import java.util.List;
import javafx.scene.control.SelectionMode;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author PHUC
 */
public class IRepository extends javax.swing.JInternalFrame {

    /**
     * Creates new form IRepository
     */
    public IRepository() {
        initComponents();
        init();
        loadData();
    }

    private List<Inventory> inventory = new ArrayList<>();
    private AbstractTableModel model;

    private void init(){
        this.tblRepository.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void loadData() {
        inventory = DatabaseAPI.getListRepository();
        this.model = new DataModelRepository(inventory);
        this.tblRepository.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepository = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnOld = new javax.swing.JButton();

        tblRepository.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tblRepository.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRepository);

        txtSearch.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnNew.setText("Nhập hàng mới");
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnOld.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnOld.setText("Nhập thêm hàng");
        btnOld.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnNew)
                    .addComponent(btnOld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String search = txtSearch.getText();
        if(!search.equals("")){
            inventory = DatabaseAPI.searchRepository(search);
            this.model.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        DNewImport dNewImport = new DNewImport(null, true, this);
        dNewImport.setResizable(false);
        dNewImport.setTitle("Nhập hàng mới");
        dNewImport.setLocationRelativeTo(this);
        dNewImport.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldActionPerformed
        // TODO add your handling code here:
        int selectedIndex = this.tblRepository.getSelectedRow();
        if(selectedIndex >= 0){
            Inventory i = this.inventory.get(selectedIndex);
            DExtraImport dExtraImport = new DExtraImport(null, true, this, i);
            dExtraImport.setLocationRelativeTo(this);
            dExtraImport.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm để nhập thêm!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOld;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRepository;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
