/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.sun.xml.internal.ws.api.message.Message;
import dao.DatabaseAPI;
import dao.HibernateUtil;
import entities.Account;
import entities.Inventory;
import java.util.Calendar;
import java.util.List;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author PHUC
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jButton1)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        DateTimePicker datePicker = new DateTimePicker();
//                datePicker.setBorder(borderUnfocusedCell);
//                datePicker.getComponentDateTextField().setBorder(null);
        // Adjust any needed date picker settings.
//                DatePickerSettings settings = datePicker.getSettings();
//                settings.setGapBeforeButtonPixels(0);
//                settings.setSizeTextFieldMinimumWidthDefaultOverride(false);
//                settings.setSizeTextFieldMinimumWidth(20)
//                datePicker.show();
        DashBoard frame = new DashBoard();
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);

        //frame.setUndecorated(true);
        frame.setVisible(true);
        frame.setResizable(false);
//        UtilDateModel model = new UtilDateModel();
//        JDatePanelImpl datePanel = new JDatePanelImpl(model);
//        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);
//        datePicker.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HibernateUtil.getSessionFactory().getCurrentSession();
                MainFrame frame = new MainFrame();
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);

                //frame.setUndecorated(true);
//                UtilDateModel model = new UtilDateModel();
//                JDatePicker datePanel = new JDatePicker(model);
//                datePanel.setVisible(true);
//                frame.getContentPane().add(datePanel);
//                frame.pack();
//                DateTimePicker datePicker = new DateTimePicker();
//                datePicker.setBorder(borderUnfocusedCell);
//                datePicker.getComponentDateTextField().setBorder(null);
                // Adjust any needed date picker settings.
//                DatePickerSettings settings = datePicker.getSettings();
//                settings.setGapBeforeButtonPixels(0);
//                settings.setSizeTextFieldMinimumWidthDefaultOverride(false);
//                settings.setSizeTextFieldMinimumWidth(20)
//                datePicker.show();
//                datePicker.setVisible(true);
//                frame.add(datePicker);
                frame.setVisible(true);
                frame.setResizable(false);
//                Inventory inventory = new Inventory();
//                inventory.setCount(20);
//                inventory.setDateImport(Calendar.getInstance().getTime());
//                     
//                List<Inventory> list = DatabaseAPI.getListRepository();
                //JOptionPane.showMessageDialog(null, list.get(0).getCount());

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
