/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package charts;

import common.CommonFunction;
import dao.DatabaseAPI;
import java.util.Date;
import java.util.List;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author PHUC
 */
public class ChartRevenue extends javax.swing.JDialog {

    private List<Date> listDates;
    private int type;
    private int data;
    private String name;
    private String label;
    private DefaultCategoryDataset dataset;

    /**
     * Creates new form ChartRevenue
     */
    public ChartRevenue(java.awt.Frame parent, boolean modal, List<Date> list, int type) {
        super(parent, modal);
        this.listDates = list;
        this.type = type;
        initComponents();
        init();
    }

    public void init() {
        this.name = "DOANH THU";
        switch (type) {
            case 0:
                this.label = CommonFunction.formatDate(this.listDates.get(0), "dd-MM-yyyy");
                break;
            case 1:
                this.label = CommonFunction.formatDate(this.listDates.get(0), "MM-yyyy");
                break;
            case 2:
                this.label = CommonFunction.formatDate(this.listDates.get(0), "yyyy");
                break;
            case 3:
                this.label = "Từ " + CommonFunction.formatDate(this.listDates.get(0), "dd-MM-yyyy")
                        + " Đến " + CommonFunction.formatDate(this.listDates.get(1), "dd-MM-yyyy");
                break;
            default:
                this.label = "";
        }
        this.data = DatabaseAPI.getRevenue(listDates, type);
        this.dataset = GenerateDataSet.generateDatasetBarChart(data, name, label);
        JFreeChart freeChart = ChartFactory.createBarChart("Thống kê doanh thu", "Thời gian", "Đơn vị(VNĐ)", dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot categoryPlot = freeChart.getCategoryPlot();
        BarRenderer br = (BarRenderer) categoryPlot.getRenderer();
        br.setMaxBarWidth(0.25);
        ChartPanel panel = new ChartPanel(freeChart);
        this.setContentPane(panel);
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
