package entities;
// Generated Dec 14, 2018 10:17:08 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "CATEGORY",
         schema = "dbo",
         catalog = "WINDOWS"
)
public class Category implements java.io.Serializable {

    @Id
    @GenericGenerator(name = "i1", strategy = "increment")
    @GeneratedValue(generator = "i1")
    @Column(name = "ID", unique = true, nullable = false)
    private int id;
    @Column(name = "MANUFACTURER")
    private String manufacturer;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
    private Set<Phone> phones = new HashSet<Phone>(0);

    public Category() {
    }

    public Category(int id) {
        this.id = id;
    }

    public Category( String manufacturer, Set<Phone> phones) {
        this.manufacturer = manufacturer;
        this.phones = phones;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getManufacturer() {
        return this.manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Set<Phone> getPhones() {
        return this.phones;
    }

    public void setPhones(Set<Phone> phones) {
        this.phones = phones;
    }

}
