package entities;
// Generated Dec 14, 2018 10:17:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "DISCOUNT",
         schema = "dbo",
         catalog = "WINDOWS"
)
public class Discount implements java.io.Serializable {

    @Id
    @GenericGenerator(name = "i1", strategy = "increment")
    @GeneratedValue(generator = "i1")
    @Column(name = "ID", unique = true, nullable = false)
    private int id;

    @Column(name = "PERCENT_DISCOUNT")
    private Integer percentDiscount;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TIME_BEGIN", length = 23)
    private Date timeBegin;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TIME_END", length = 23)
    private Date timeEnd;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "discount")
    private Set<Bill> bills = new HashSet<Bill>(0);

    public Discount() {
    }

    public Discount(int id) {
        this.id = id;
    }

    public Discount(Integer percentDiscount, Date timeBegin, Date timeEnd, Set<Bill> bills) {
        this.percentDiscount = percentDiscount;
        this.timeBegin = timeBegin;
        this.timeEnd = timeEnd;
        this.bills = bills;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Integer getPercentDiscount() {
        return this.percentDiscount;
    }

    public void setPercentDiscount(Integer percentDiscount) {
        this.percentDiscount = percentDiscount;
    }

    public Date getTimeBegin() {
        return this.timeBegin;
    }

    public void setTimeBegin(Date timeBegin) {
        this.timeBegin = timeBegin;
    }

    public Date getTimeEnd() {
        return this.timeEnd;
    }

    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    public Set<Bill> getBills() {
        return this.bills;
    }

    public void setBills(Set<Bill> bills) {
        this.bills = bills;
    }

}
