package entities;
// Generated Dec 14, 2018 10:17:08 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name = "INVENTORY",
        schema = "dbo",
        catalog = "WINDOWS"
)
public class Inventory implements java.io.Serializable {

    @Id

    @GenericGenerator(name = "i1", strategy = "increment")
    @GeneratedValue(generator = "i1")
    @Column(name = "STT", unique = true, nullable = false)
    private int stt;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_PHONE")
    private Phone phone;

    @Column(name = "COUNT")
    private Integer count;

    @Temporal(TemporalType.DATE) 
    @Column(name = "DATE_IMPORT")
    private Date dateImport;

    public Inventory() {
    }

    public Inventory(int stt) {
        this.stt = stt;
    }

    public Inventory(Phone phone, Integer count, Date dateImport) {

        this.phone = phone;
        this.count = count;
        this.dateImport = dateImport;
    }

    public int getStt() {
        return this.stt;
    }

    public void setStt(int stt) {
        this.stt = stt;
    }

    public Phone getPhone() {
        return this.phone;
    }

    public void setPhone(Phone phone) {
        this.phone = phone;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Date getDateImport() {
        return this.dateImport;
    }

    public void setDateImport(Date dateImport) {
        this.dateImport = dateImport;
    }

}
