package entities;
// Generated Dec 14, 2018 10:17:08 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "PAYMENT",
         schema = "dbo",
         catalog = "WINDOWS"
)
public class Payment implements java.io.Serializable {

    @Id

    @GenericGenerator(name = "i1", strategy = "increment")
    @GeneratedValue(generator = "i1")
    @Column(name = "ID", unique = true, nullable = false)
    private int id;

    @Column(name = "METHOD")
    private String method;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "payment")
    private Set<Bill> bills = new HashSet<Bill>(0);

    public Payment() {
    }

    public Payment(int id) {
        this.id = id;
    }

    public Payment(String method, Set<Bill> bills) {
        this.method = method;
        this.bills = bills;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public Set<Bill> getBills() {
        return this.bills;
    }

    public void setBills(Set<Bill> bills) {
        this.bills = bills;
    }

}
